parameters:
  osName: ''
  testFramework: ''
  testTarget: ''
  configuration: ''
  powerShellPlatform: ''

steps:
- template: download-build-steps.yml
  parameters:
    artifactName: build-${{ parameters.testFramework }}
- task: NodeTool@0
  condition: eq(variables.IsGenerateBased, true)
  displayName: Install Autorest
  inputs:
    versionSpec: '14.17.1'
    command: custom
    verbose: false
    customCommand: install autorest@latest
- task: PowerShell@2
  condition: eq(variables.IsGenerateBased, true)
  displayName: Setup environment for Autorest
  inputs:
    targetType: inline
    script: "$env:NODE_OPTIONS=\"--max-old-space-size=65536\""
    pwsh: true

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.x

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: custom
    custom: msbuild
    arguments: 'build.proj /t:${{ parameters.testTarget }} /p:Configuration=${{ parameters.configuration }};TestFramework=${{ parameters.testFramework }};PullRequestNumber=$(System.PullRequest.PullRequestNumber)'
  env:
      OCTOKITPAT: $(OCTOKITPAT)
      PowerShellPlatform: ${{ parameters.powerShellPlatform }}

- powershell: |
   Install-Module -Name Pester -RequiredVersion 4.10.1 -Force -SkipPublisherCheck
   Import-Module (Join-Path -Path . -ChildPath Az.Accounts | Join-Path -ChildPath Az.Accounts.psd1) -Force
   $env:PSModulePath = $env:PSModulePath + ";" + (pwd).Path
   Get-ChildItem -File -Recurse -Depth 1 test-module.ps1 | ForEach-Object {. $_; if ($LastExitCode -ne 0) {throw "test fails when executing $_"}}
  workingDirectory: 'artifacts/Debug'
  displayName: Test for AutoGen Modules With Windows PowerShell
  condition: and(succeeded(), ne('${{ parameters.testTarget }}', 'Test'))

- pwsh: |
   Install-Module -Name Pester -RequiredVersion 4.10.1 -Force
   Import-Module (Join-Path -Path . -ChildPath Az.Accounts | Join-Path -ChildPath Az.Accounts.psd1) -Force
   if ($IsWindows) { $sp = ";" } else { $sp = ":" }
   $env:PSModulePath = $env:PSModulePath + $sp + (pwd).Path
   Get-ChildItem -File -Recurse -Depth 1 test-module.ps1 | ForEach-Object {. $_; if ($LastExitCode -ne 0) {throw "test fails when executing $_"}}
  workingDirectory: 'artifacts/Debug'
  displayName: 'Test for AutoGen Modules With PowerShell Core'
  condition: and(succeeded(), eq('${{ parameters.testTarget }}', 'Test'))

- task: PowerShell@2
  displayName: Process test coverage data
  inputs:
    pwsh: true
    targetType: filePath
    filePath: ./tools/TestFx/Coverage/ProcessCITestCoverage.ps1
    arguments: -RepoLocation $(Build.SourcesDirectory) -DataLocation $(TestCoverageLocation) -BuildId $(Build.BuildId)
  condition: succeeded()

- task: PowerShell@2
  displayName: Save test coverage data to Kusto
  inputs:
    pwsh: true
    targetType: filePath
    filePath: ./tools/TestFx/Coverage/SaveCITestCoverage.ps1
    arguments: $(KustoServicePrincipalTenantId) $(KustoServicePrincipalId) $env:KustoServicePrincipalSecret $(KustoClusterName) $(KustoClusterRegion) $(TestCoverageDatabaseName) $(TestCoverageTableName) $(TestCoverageLocation)
  env:
    KustoServicePrincipalSecret: $(KustoServicePrincipalSecret)
  condition: succeeded()

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- template: publish-artifacts-steps.yml
  parameters:
    artifactName: test-${{ parameters.testFramework }}-${{ parameters.osName }}
